### ISSUE TITLE
"Open" button not clickable, "Learn" command not recognized

### ISSUE THREAD

**Issue by tchen95** [learn-co-curriculum/first-lab-ruby-learn-cli-ile#11]
Hi, I think I'm having compatibility issues with the new Learn IDE. I can't click on the "Open" button on the toolbar, and the "learn" command is no longer recognizable to my system. The "learn" command was not an issue before. Any suggestions for fixing these issues?

**Comment by AnnJohn** [comment]
hi @tchen95 sorry for the delay with this. If you haven't yet resolved this issue, could you please use the Ask a Question tool? We use this space specifically for issues related to the content of the lessons. Thanks!
