### ISSUE TITLE
can not work

### ISSUE THREAD

**Issue by cprietoah** [learn-co-curriculum/first-lab-ruby-learn-cli-ile#15]
Hello, i'm trying to commplet learn, but was not possible! I recibe a wrong message. HELP!!
<img width="627" alt="peimer error" src="https://cloud.githubusercontent.com/assets/19936867/16327119/3a99fcbc-3992-11e6-9e3a-d67bb8e731c8.png">

**Comment by pletcher** [comment]
Thanks for opening this issue!

Keep in mind that this space is for specific issues related to the _content_ of this lesson. If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

Please be sure to include steps to reproduce (be as detailed as possible) and any relevant information about your environment. (Are you using the Learn IDE? Coding on a refurbished toaster?) We'll be sure to figure out what's going on — and to jump in and help — just as soon as we can. Thanks!

**Comment by cprietoah** [comment]
why did you close it?

**Comment by pletcher** [comment]
@cprietoah this is a product issue -- following the instructions in this repository (clicking on the "open" button, etc.), I'm unable to reproduce it. You'll get a much faster response (and be able to move forward) by reporting this as a bug on Learn. Thanks!
