### ISSUE TITLE
launching learn IDE

### ISSUE THREAD

**Issue by jlew826** [learn-co-curriculum/first-lab-ruby-learn-cli-ile#17]
when I clicked "open",  my terminal and sublime text launched, but not the Learn IDE that was described in the previous section...not sure if this is to be expected?

**Comment by pletcher** [comment]
Thanks for opening this issue!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

Please be sure to include steps to reproduce (be as detailed as possible) and any relevant information about your environment. (Are you using the Learn IDE? Coding on a refurbished toaster?) We'll be sure to figure out what's going on — and to jump in and help — just as soon as we can. Thanks!

**Comment by jlew826** [comment]
just realized that I did not choose the Learn IDE option as my "DEVELOPMENT ENVIRONMENT" in my learn profile... please disregard my previous comment :)

**Comment by pletcher** [comment]
👯
