### ISSUE TITLE
my terminal is not showing me the correct info

### ISSUE THREAD

**Issue by zendine** [learn-co-curriculum/first-lab-ruby-learn-cli-ile#2]
[13:23:13] code  
// ♥ learn open first-lab-ruby-learn-cli-ile-intro-to-learn  
Looking for lesson...  
Forking lesson...  
Cloning lesson...  
There was a problem cloning this lesson. Retrying...  
Cloning lesson...  
There was a problem cloning this lesson. Retrying...  
Cloning lesson...  
Cloning lesson...  
Cannot clone this lesson right now. Please try again.  
[13:23:18] code  
// ♥

**Comment by AnnJohn** [comment]
hi @zendine. can you please use the Ask a Question tool and someone will get back to you right away? thanks!

**Comment by zendine** [comment]
hi there, i ve tried the ask a question tool, but no one had responded to me yet.
