### ISSUE TITLE
Lesson 10 First Lab

### ISSUE THREAD

**Issue by Class2015** [learn-co-curriculum/first-lab-ruby-learn-cli-ile#3]
Clicking on the open button for lesson 10 does not work. I can only access the GitHub button adjacent to it. What now?

**Comment by AnnJohn** [comment]
hi @Class2015  this is definitely a technical issue with the IDE. Can you file a bug report? If you hover over your profile pic in Learn, you'll see an option to file a bug report from a dropdown menu.

You can also email support+ide@learn.co for help as well. Thanks!
