### ISSUE TITLE
No edit-me.txt file in the lab folder

### ISSUE THREAD

**Issue by katekisiel** [learn-co-curriculum/first-lab-ruby-learn-cli-ile#4]
I didn't see the file edit-me.txt in the first lab folder so I created it but it didn't seem to work
<img width="1280" alt="screen shot 2016-05-06 at 5 49 05 pm" src="https://cloud.githubusercontent.com/assets/19214348/15086977/e7aa8904-13b2-11e6-8bf8-f94800a39908.png">

**Comment by AnnJohn** [comment]
hi @katekisiel this is definitely a technical issue with the IDE. Can you file a bug report? If you hover over your profile pic in Learn, you'll see an option to file a bug report from a dropdown menu. 

You can also email  support+ide@learn.co for help as well. Thanks!
