### ISSUE TITLE
Nothing happens when I click on the Open tab

### ISSUE THREAD

**Issue by jacqueline-homan** [learn-co-curriculum/first-lab-ruby-learn-cli-ile#5]
No IDE starts up
No nothing.

**Comment by AnnJohn** [comment]
hi there. sorry for the delay and the issue you're having. We use this space for issues specifically related to content in the lessons, so if this hasn't already been resolved can you please use the Ask a Question tool or file a bug report? If you click on your profile pic on Learn, you'll see an option to report a bug?
