### ISSUE TITLE
lab not found

### ISSUE THREAD

**Issue by oaobi** [learn-co-curriculum/first-lab-ruby-learn-cli-ile#6]
Attempted to "Open" the lab on Learn.co, and it's not found. I'll fork it to my Github and try to work around this until I hear back. 

![screen shot 2016-06-02 at 10 07 47 pm](https://cloud.githubusercontent.com/assets/19714005/15766640/b0849afc-290e-11e6-89b0-fbca318ad824.png)

Used the work around to manually do the workflow. Forked the file in Github, copied it to my local drive, solved it, pushed it back to Github, and submitted a pull request. However, because the local tests need to be run through the expedited workflow, I can't complete the lesson.

![screen shot 2016-06-02 at 11 12 41 pm](https://cloud.githubusercontent.com/assets/19714005/15767621/a3571c66-2917-11e6-9365-365a56a2f207.png)

I also tried to [learn submit] first rather than push the files to Github, and it wouldn't actually complete the process. 

![screen shot 2016-06-02 at 11 15 55 pm](https://cloud.githubusercontent.com/assets/19714005/15767685/19aad650-2918-11e6-97f9-525811a37f14.png)
![screen shot 2016-06-02 at 11 16 08 pm](https://cloud.githubusercontent.com/assets/19714005/15767686/19b885fc-2918-11e6-9c3f-5c38664467dd.png)

Help would be appreciated.

**Comment by AnnJohn** [comment]
hi @oaobi sorry for the trouble that you're having. This is a technical issue that's specific to you so could you please use the Ask a Question tool and someone from our Learn Experts team will help you out. Thanks.
