### ISSUE TITLE
Finished and submitted but not marked as pass

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/first-lab-ruby-learn-cli-ile#7]
Finished and submitted but not marked as pass on the Learn.co site

**Comment by AnnJohn** [comment]
hi there. sorry for the delay and the issue you're having. We use this space for issues specifically related to content in the lessons, so if this hasn't already been resolved can you please use the Ask a Question tool or file a bug report? If you click on your profile pic on Learn, you'll see an option to report a bug?
